### PR TITLE
support RESIZE_BILINEAR op

### PR DESCRIPTION
**Pull request by pinzhenx**
Fix intel/webml-polyfill#338

### CODE REVIEW

**Comment by pinzhenx** [comment]
I have also changed one line in the implementation of `resizeBilinearPrepare()` which has the signature of `(input, width, height, output)`.

However, the declaration in the [header file](https://android.googlesource.com/platform/frameworks/ml/+/master/nn/common/include/OperationsUtils.h#243) is `(input, height, width, output)`. Same as its definition in the [API doc](https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a42bd92518e273b6716ecd56b571fcd3e) and the definition of [tensorflow API](https://www.tensorflow.org/api_docs/python/tf/image/resize_bilinear).

Because of the `NHWC` order, I think the `(input, height, width, output)` is a more natural definition.

**Comment by huningxin** [comment]
related to https://github.com/intel/webml-polyfill/pull/343

**Comment by huningxin** [comment]
> Because of the `NHWC` order, I think the `(input, height, width, output)` is a more natural definition.

I agree. It looks like an issue in AOSP. Could you please investigate whether the latest code fix that? Otherwise, we may file a bug to AOSP.

**Comment by huningxin** [comment]
PR LGTM. Thanks!

**Pull request merged**
